import Footer from "@/shared/ui/Footer";
import Header from "@/shared/ui/Header";
import TabsNav from "@/shared/ui/TabsNav/TabsNav";
import Head from "next/head";
import Image from 'next/image';
import Link from "next/link";
import React, { useEffect, useState } from 'react';

const PRODUCTS = [
  {id: 1, name: "Стильная худи"},
  {id: 2, name: "кроссовки"},
  {id: 3, name: "рюкзак"},
]

export default function Home() {
const [openMenu, setOpenMenu] = useState(false)

  const [cart, setCart] = useState([])
  const [isModalOpen, setIsModalOpen] = useState(false)
  const [isMounted, setIsMounted] = useState(false)

  useEffect(() => {
     const savedCart = localStorage.getItem("shopping-cart")
     if(savedCart){
      setCart(JSON.parse(savedCart))
     }
     setIsMounted(true)
  }, [])

  useEffect(() => {
    if(isMounted){
      localStorage.setItem("shopping-cart", JSON.stringify(cart))
    }
  }, [cart, isMounted])

  const addToCart = (product) => {
    const existingItem = cart.find(item => item.id)
    if(existingItem){
      setCart(cart.map(item => 
        item.id === product.id ? {...item, quantity: item + 1} : item
      ))
    }else{
      setCart([...cart, {...product, quantity: 1}])
    }
    setIsModalOpen(true)
  }

  const removeFromCart = (productId) => {
    setCart(cart.filter(item.id !== productId))
  }

  // slider--
  const promotionsData = [
  {
    id: "1",
    number: "01",
    tag: "для нормальной кожи",
    title: "Invisible symphony — ваша волшебная палочка для борьбы с несовершенствами",
    description: "Сочетая энергию природы и возможности науки восстанавливает вашу кожу, помогает регенерации клеток, разглаживает рельеф, интенсивно увлажняет надолго.",
    imageUrl: "/img/jar1.svg",
  },
  {
    id: "2",
    number: "02",
    tag: "2",
    title: "Invisible symphony — ваша волшебная палочка для борьбы с несовершенствами",
    description: "Сочетая энергию природы и возможности науки восстанавливает вашу кожу, помогает регенерации клеток, разглаживает рельеф, интенсивно увлажняет надолго.",
    imageUrl: "/img/jar3.png",
  },
  {
    id: "3",
    number: "3",
    tag: "2",
    title: "Invisible symphony — ваша волшебная палочка для борьбы с несовершенствами",
    description: "Сочетая энергию природы и возможности науки восстанавливает вашу кожу, помогает регенерации клеток, разглаживает рельеф, интенсивно увлажняет надолго.",
    imageUrl: "/img/sk.png",
  },
];

  const [currentIndex, setCurrentIndex] = useState(0);

  const nextSlide = () => {
    setCurrentIndex((prev) => (prev + 1) % promotionsData.length);
  };

  const prevSlide = () => {
    setCurrentIndex((prev) => (prev - 1 + promotionsData.length) % promotionsData.length);
  };

  const currentPromo = promotionsData[currentIndex];
  // slider--

  return (
    <>
       <Head>
        <title>Магазин натуральной косметики  </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <main>
           <section className="white">
               <header>
            <div className="header_menu">
                <ul className={`header_lst ${openMenu ? "active": ""}`}>
                   <li>
                    <Link href="#" className="lnk_3">
                    о продукте
                    </Link>
                   </li>
                   <li>
                    <Link href="#" className="lnk_3">
                     Каталог
                    </Link>
                   </li>
                   <li>
                    <Link href="#" className="lnk_3">
                     Акции
                    </Link>
                   </li>
                   <li>
                    <Link href="#" className="lnk_3">
                     Полезное
                    </Link>
                   </li>
                   <li>
                    <Link href="#" className="lnk_3">
                     Авторы
                    </Link>
                   </li>
                   <li className="close" onClick={() => setOpenMenu(false)}>
                    выйти
                   </li>
                </ul>
                <div className="header_menu" onClick={() => setOpenMenu(!openMenu)}>
                    <img src="./img/menu.svg" alt="" />
                </div>
            </div>

            <div className="header_left">
              <div className="header_logo">
                <div className="header_logo_itm">
                  <img src="./img/D.svg" alt="" />
                </div>
              </div>

                <ul className="header_list">
                    <li>
                        <Link href="#" className="lnk">
                          О продукте
                        </Link>
                    </li>

                    <li>
                        <Link href="#" className="lnk">
                          Каталог
                        </Link>
                    </li>

                    <li>
                        <Link href="#" className="lnk">
                          Акции
                        </Link>
                    </li>

                    <li>
                        <Link href="#" className="lnk">
                          Полезное
                        </Link>
                    </li>

                    <li>
                        <Link href="#" className="lnk">
                          Авторы
                        </Link>
                    </li>
                </ul>
            </div>

            <div className="header_rigth">
                <div className="header_cart">
                   <div className="hdr_lm">
                     <img src="./img/cart.svg" alt="" />
                   </div>
                    <div className="header_counter" onClick={() => setIsModalOpen(true)}>
                      <p className="txt_1">
                        ({isMounted ? cart.reduce((sum, item) => sum + item.quantity, 0): 0})
                      </p>
                    </div>
                </div>

                <div className="header_rigth_itm">
                    <Link href="#" className="lnk_2">
                    Instagram
                    </Link>
                    <Link href="#" className="lnk_2">
                    Facebook
                    </Link>
                </div>
            </div>  
        </header>
            <div className="container">
               
               <div className="banner">

                <div className="kisspng">
                  <img src="./img/kisspng.svg" alt="" />
                </div>

               <div className="banner_left">
                 <h1 className="banner_txt">Diamaint</h1>

                 <div className="banner_b">
                  <p className="banner_txt_2">
                  Натуральная <br />
                  косметика <br />
                  с привкусом <br />
                  Ирландии
                 </p>


                 <div>
                  <p className="banner_txt_3">
                  Diamaint — одуванчик в переводе <br />
                   с ирландского
                 </p>

                 <p className="banner_txt_4">
                  Косметика, после которой вы уже <br />
                   никогда не будете прежней и обретёте <br />
                   новую жизнь, где наша продукция будет <br />
                   вашим верным спутником и <br />
                    помощником
                 </p>

                 <p className="banner_txt_4">
                  Используем всю силу природы, а так же <br />
                   новейшие разработки индустрии вкупе  <br />
                   традиционными ирландскими  <br />
                   рецептами для того, чтобы придать  <br />
                   вашей коже здоровый и цветущий вид
                 </p>

                 <button className="btn">
                  <Link href="#" className="lnk_4">
                  Выбрать продукт
                  </Link>
                 </button>
                 </div>

                 </div>
               </div>



               <div className="dandelion">
                <img src="./img/Dandelion.png" alt="" />
               </div>
               </div>

            </div>
           </section>

           <section className="white">
            <div className="container">
              <div className="diamint_block">
                  <p className="txt_2">
                    Ингридиенты контролируются по  <br />
                   качеству и происхождению. <br />
                   Большинство из них имеют органический сертификат Ecoсert и Soil  <br />
                   Association. Сочетание компонентов в   <br />
                    каждой линейке подобрано с учетом   <br />
                    особенностей типа кожи.
                  </p>


                  <div className="diamint_righth">
                     <p className="txt_3">
                      Diamaint — только  <br />
                      натуральные   <br />
                      ингридиенты
                     </p>

                     <div className="joanna">
                      <img src="./img/joanna.png" alt="" />
                     </div>
                  </div>
              </div>
            </div>
           </section>

           <section className="white">
            <div className="container">
              <div className="product_block">
                <p className="txt_4">Выбери свой продукт</p>

                <div className="product_grid">
                  <div className="product_itm">
                    <div className="product_top_itm">
                      <img src="./img/sk.svg" alt="" />
                    </div>

                     <div className="product_top">
                      <img src="./img/jar1.svg" alt="" />
                     </div>

                     <div className="product_bottom">
                      <p className="txt_5">для нормальной кожи</p>
                      <p className="txt_6">
                         Увлажняющая <br />
                         маска
                      </p>

                      <div className="pdct_b">
                        <p className="txt_7">
                          <span className="spn">3 750</span>   3500 ₽
                        </p> 

                        <button className="btn_cart">
                          <img src="./img/crt_btn.svg" alt="" />
                        </button>
                      </div>
                     </div>
                  </div>
 
                     <div className="product_itm">

                     <div className="product_top">
                      <img src="./img/jar3.png" alt="" />
                     </div>

                     <div className="product_bottom">
                      <p className="txt_5">для нормальной кожи</p>
                      <p className="txt_6">
                         Увлажняющая <br />
                         маска
                      </p>

                      <div className="pdct_b">
                        <p className="txt_7">
                          <span className="spn">3 750</span>   3500 ₽
                        </p> 

                        <button className="btn_cart">
                          <img src="./img/crt_btn.svg" alt="" />
                        </button>
                      </div>
                     </div>
                  </div>
                    
                     <div className="product_itm">

                     <div className="product_top">
                      <img src="./img/jar3.png" alt="" />
                     </div>

                     <div className="product_bottom">
                      <p className="txt_5">для нормальной кожи</p>
                      <p className="txt_6">
                         Увлажняющая <br />
                         маска
                      </p>

                      <div className="pdct_b">
                        <p className="txt_7">
                          <span className="spn">3 750</span>   3500 ₽
                        </p> 

                        <button className="btn_cart">
                          <img src="./img/crt_btn.svg" alt="" />
                        </button>
                      </div>
                     </div>
                  </div>

                </div>
              </div>

            </div>
           </section>


           <section className="white">
            <div className="container">
              <div className="sldr_block">
                <div className="promo-wrapper">
        
        {/* Левая колонка */}
        <div className="promo-info">
          <div>
            <h2 className="promo-title">Акции</h2>
            <p className="promo-subtitle">
              Каждый месяц мы отбираем специальную линейку продуктов, которая нравится вам и снижаем цены!
            </p>
          </div>

          {/* Стрелки переключения */}
          <div className="promo-controls">
            <button
              onClick={prevSlide}
              className="promo-btn"
              aria-label="Предыдущий слайд"
            >
              <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1} stroke="currentColor" style={{ width: '20px', height: '20px' }}>
                <path strokeLinecap="round" strokeLinejoin="round" d="M15.75 19.5L8.25 12l7.5-7.5" />
              </svg>
            </button>
            <button
              onClick={nextSlide}
              className="promo-btn"
              aria-label="Следующий слайд"
            >
              <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1} stroke="currentColor" style={{ width: '20px', height: '20px' }}>
                <path strokeLinecap="round" strokeLinejoin="round" d="M8.25 4.5l7.5 7.5-7.5 7.5" />
              </svg>
            </button>
          </div>
        </div>

        {/* Правая колонка */}
        <div className="promo-showcase">
          
          {/* Вертикальный тег */}
          <div className="promo-badge-vertical">
            <span className="promo-badge-text">
              {currentPromo.tag}
            </span>
          </div>

          {/* Карточка предложения */}
          <div className="promo-card">
            
            <div className="promo-card-content">
              <div className="promo-card-index">
                {currentPromo.number}
              </div>
              <h3 className="promo-card-title">
                {currentPromo.title}
              </h3>
              <p className="promo-card-text">
                {currentPromo.description}
              </p>
            </div>

            {/* Изображение товара */}
            <div className="promo-image-box">
              <Image
                src={currentPromo.imageUrl}
                alt={currentPromo.title}
                fill
                priority
                sizes="(max-width: 768px) 192px, 224px"
                style={{ objectFit: 'contain' }}
              />
            </div>

          </div>

        </div>

      </div>
              </div>
            </div>
           </section>

           <section className="white">
            <div className="container">
              <div className="discounts_block">
                <div className="branch_1">
                  <img src="./img/branch_1.svg" alt="" />
                </div>

                 <div className="discounts_flex">
                  <div className="discounts_itm_1">
                   <div className="discounts_top">
                    <p className="discounts_txt">СКИДКА 5%</p>
                   </div>

                   <div className="discount_photo">
                    <img src="./img/d_1.png" alt="" />
                   </div>

                   <div className="discount_bottom">
                    <p className="discounts_txt_2">
                      Приобретая увлажняющий <br />
                       крем и маску, вы получаете  <br />
                      скидку 5% на весь товар
                    </p>

                    <div className="discount_bl">
                        <p class="txt_7">
                          <span class="spn">3 750</span>3500 ₽
                          </p>

                       <button class="btn_cart">
                        <img src="./img/crt_btn.svg" alt=""/>
                        </button>
                    </div>
                   </div>
                  </div>

                    <div className="discounts_itm_2">
                   <div className="discounts_top">
                    <p className="discounts_txt">СКИДКА 5%</p>
                   </div>

                   <div className="discount_photo">
                    <img src="./img/d_1.png" alt="" />
                   </div>

                   <div className="discount_bottom">
                    <p className="discounts_txt_2">
                      Приобретая увлажняющий <br />
                       крем и маску, вы получаете  <br />
                      скидку 5% на весь товар
                    </p>

                    <div className="discount_bl">
                        <p class="txt_7">
                          <span class="spn">3 750</span>3500 ₽
                          </p>

                       <button class="btn_cart">
                        <img src="./img/crt_btn.svg" alt=""/>
                        </button>
                    </div>
                   </div>
                  </div>
                    
                     <div className="discounts_itm_3">
                   <div className="discounts_top">
                    <p className="discounts_txt">СКИДКА 5%</p>
                   </div>

                   <div className="discount_photo">
                    <img src="./img/d_1.png" alt="" />
                   </div>

                   <div className="discount_bottom">
                    <p className="discounts_txt_2">
                      Приобретая увлажняющий <br />
                       крем и маску, вы получаете  <br />
                      скидку 5% на весь товар
                    </p>

                    <div className="discount_bl">
                        <p class="txt_7">
                          <span class="spn">3 750</span>3500 ₽
                          </p>

                       <button class="btn_cart">
                        <img src="./img/crt_btn.svg" alt=""/>
                        </button>
                    </div>
                   </div>
                  </div>
                  
                 </div>
              </div>
            </div>
           </section>

           <section className="white">
            <div className="container">
              <div className="banner_2">
                 

                    <div className="banner_2_elem">
                      <div className="bnr_2">
                        <img src="./img/bnr_2.svg" alt="" />
                      </div>


                      <div className="bnr_left">
                         <p className="txt_8">
                          Протестировали и  <br />
                          довольны результатом
                         </p>

                         <p className="txt_9">
                            6800
                         </p>
                          <span className="sp_2">Женщин</span>

                          <p className="txt_10">
                            96% женщин заметили положительный результат уже   <br />
                            после недели использования линейки средств. Кожа  <br />
                             стала более ухоженной, увлажненной и напитанной.    <br />
                            Исчезли или значительно уменьшились воспаления.   <br />
                           А приятный аромат и легкая текстура стали   <br />
                           отличным дополнением с утренне-вечерним  <br />
                            ритуалам ухода
                          </p>

                          <p className="txt_11">
                            Diamaint
                          </p>
                      </div>
                    </div>
              </div>
            </div>
           </section>

           <section className="white">
            <div className="container">
              <div className="bl_1">
                <p className="txt_12">Полезно узнать</p>

                <div className="bl_2">
                   
                    
    <div class="card_2">
 
  <div class="card-body_2">
    <span class="category_2">Совет</span>
    <h3 class="title">Как выбрать <br />
     крем
    </h3>
    <p class="description_2">
      7 критериев правильного выбора. Под воздействием окружающей среды...
    </p>
  </div>

 
  <div class="card-footer_2">
    <span class="line"></span>
    <Link href="#" class="read-more">ЧИТАТЬ</Link>
  </div>
</div>
   
    <div className="crd_centr">
       <div class="card">
 
  <div class="card-body">
    <span class="category">Совет</span>
    <h3 class="title">Как выбрать <br />
     крем
    </h3>
    <p class="description">
      7 критериев правильного выбора. Под воздействием окружающей среды...
    </p>
  </div>

 
  <div class="card-footer">
    <span class="line"></span>
    <Link href="#" class="read-more">ЧИТАТЬ</Link>
  </div>
</div>

       <div class="card">
 
  <div class="card-body">
    <span class="category">Совет</span>
    <h3 class="title">Как выбрать <br />
     крем
    </h3>
    <p class="description">
      7 критериев правильного выбора. Под воздействием окружающей среды...
    </p>
  </div>

 
  <div class="card-footer">
    <span class="line"></span>
    <Link href="#" class="read-more">ЧИТАТЬ</Link>
  </div>
</div>
    </div>

            <div class="card">
 
  <div class="card-body">
    <span class="category">Совет</span>
    <h3 class="title">Как выбрать <br />
     крем
    </h3>
    <p class="description">
      7 критериев правильного выбора. Под воздействием окружающей среды...
    </p>
  </div>

 
  <div class="card-footer">
    <span class="line"></span>
    <Link href="#" class="read-more">ЧИТАТЬ</Link>
  </div>
</div>


                </div>
              </div>
            </div>
           </section>


           <section className="white">
            <div className="container">
              <div className="avtor_block">
                  <div className="avtor_left">
                     <p className="txt_16">
                    Авторы и <br />
                     идеологи
                   </p>

                   <p className="txt_17">Маша Шестякова</p>
                   <p className="txt_18">
                    Маша — главный идеолог, создатель проекта и по совместительству главный   <br />
                    добытчик рецептов. Машиной фишкой является бабушка-ирландка, бывшая   <br />
                    модель с бесконечным запасом проверенных на себе народных рецептов. 
                   </p>

                   <div className="txt_block">
                    <p className="txt_20">“</p>

                    <p className="txt_19">
                      Мне нравится адаптировать культуру моих предков к   <br />
                      современности. Я чувствую, что создаю нить между  <br />
                      разными эпохами. И то, что мой продукт делает  <br />
                      девушек красивыми и уверенными в себе, помогает  <br />
                       мне чувствовать себя счастливой!
                    </p>
                   </div>

                   <div className="avtor_flex">
                    <div className="avtor_itm">
                      <img src="./img/ntrl_1.svg" alt="" />
                    </div>

                    <div className="avtor_itm">
                      <img src="./img/ntrl_2.svg" alt="" />
                    </div>

                    <div className="avtor_itm">
                      <img src="./img/ntrl_3.svg" alt="" />
                    </div>
                   </div>
                  </div>
                  
                  <div className="avtor_rigth">
                    <img src="./img/ntrlBg.png" alt="" />
                  </div>
              </div>
            </div>
           </section>

           <section className="ft">
            <div className="container">
             <Footer/>
            </div>
           </section>
        </main>
      </div> 
     </>
  );
} 


